package cr.ac.una.services.impl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-08-20T20:22:19.252-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://impl.services.una.ac.cr/", name = "UserServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceImpl {

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/createUserRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.Response createUser(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.services.impl.UserDto arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/getUserByIdRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/getUserByIdResponse")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.Response getUserById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/deleteUserByIdRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/deleteUserByIdResponse")
    @RequestWrapper(localName = "deleteUserById", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.DeleteUserById")
    @ResponseWrapper(localName = "deleteUserByIdResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.DeleteUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.Response deleteUserById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/updateUserByIdRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/updateUserByIdResponse")
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.UpdateUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.Response updateUserById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        cr.ac.una.services.impl.UserDto arg1
    );
}
