package cr.ac.una.services.impl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-08-19T19:41:07.245-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://impl.services.una.ac.cr/", name = "UserServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceImpl {

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/createUserRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.User createUser(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.services.impl.User arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/getUserByIdRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/getUserByIdResponse")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.impl.User getUserById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/deleteUserRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/deleteUserResponse")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.DeleteUserResponse")
    public void deleteUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://impl.services.una.ac.cr/UserServiceImpl/updateUserRequest", output = "http://impl.services.una.ac.cr/UserServiceImpl/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://impl.services.una.ac.cr/", className = "cr.ac.una.services.impl.UpdateUserResponse")
    public void updateUser(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.services.impl.User arg0
    );
}
