-- Usage
CALL EVACOMUNA.CHANGE_PASSWORD(:USER_ID, :NEW_PASSWORD);

-- Procedure
CREATE OR REPLACE PROCEDURE CHANGE_PASSWORD (
    USER_ID IN NUMBER,
    NEW_PASSWORD IN VARCHAR2
) AS
BEGIN
    UPDATE TBL_USER
    SET
        PASSWORD = NEW_PASSWORD
    WHERE
        ID = USER_ID;
    COMMIT;
END CHANGE_PASSWORD;