-- Usage
CALL EVACOMUNA.GENERATE_RANDOM_PASSWORD(:USER_ID);

-- Procedure
CREATE OR REPLACE PROCEDURE GENERATE_RANDOM_PASSWORD (
    USER_ID IN NUMBER
) AS
    NEW_PASSWORD VARCHAR2(16);
BEGIN
    NEW_PASSWORD := DBMS_RANDOM.STRING('x', 16);
    UPDATE TBL_USER
    SET
        PASSWORD = NEW_PASSWORD
    WHERE
        ID = USER_ID;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('New Password: '
                         || NEW_PASSWORD);
END GENERATE_RANDOM_PASSWORD;