-- Usage
CALL EVACOMUNA.GENERATE_RANDOM_PASSWORD(:USER_ID);

-- Procedure
CREATE OR REPLACE PROCEDURE EVACOMUNA.GENERATE_RANDOM_PASSWORD(
    USER_ID IN NUMBER
) AS
BEGIN
    UPDATE TBL_USER
    SET
        PASSWORD = DBMS_RANDOM.STRING(
            'x',
            10
        )
    WHERE
        ID = USER_ID;
    COMMIT;
END GENERATE_RANDOM_PASSWORD;