-- create the user
CREATE USER EVACOMUNA
  IDENTIFIED BY UNA
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;

-- grant/revoke role privileges
GRANT RESOURCE TO EVACOMUNA;

GRANT CONNECT TO EVACOMUNA;

GRANT DBA TO EVACOMUNA;

-- grant/revoke system privileges
GRANT CREATE SESSION TO EVACOMUNA;

GRANT UNLIMITED TABLESPACE TO EVACOMUNA;