-- TABLES

-- TABLE COMPANY
CREATE TABLE EVACOMUNA."TBL_COMPANY" (
    "ID" NUMBER(38, 0) NOT NULL ENABLE,
    "NAME" VARCHAR2(32) NOT NULL ENABLE,
    "EMAIL" VARCHAR2(64) NOT NULL ENABLE,
    "PHOTO" BLOB NOT NULL ENABLE,
    CONSTRAINT "TBL_COMPANY_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" LOB (
    "PHOTO"
) STORE AS SECUREFILE (
    TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES
);

-- TABLE EVALUATION
CREATE TABLE EVACOMUNA."TBL_EVALUATION" (
    "ID" NUMBER(38, 0) NOT NULL ENABLE,
    "NAME" VARCHAR2(24) NOT NULL ENABLE,
    "INITIALPERIOD" DATE NOT NULL ENABLE,
    "FINALPERIOD" DATE NOT NULL ENABLE,
    "APPLICATIONDATE" DATE NOT NULL ENABLE,
    "STATE" VARCHAR2(24) DEFAULT 'under construction' NOT NULL ENABLE,
    CONSTRAINT "TBL_EVALUATION_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TBL_EVALUATION_CHECK" CHECK ( STATE IN ( 'under construction', 'in application', 'under review', 'completed' ) ) ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- TABLE TBL_SKILL
CREATE TABLE EVACOMUNA."TBL_SKILL" (
    "ID" NUMBER(38, 0) NOT NULL ENABLE,
    "NAME" VARCHAR2(24) NOT NULL ENABLE,
    "STATE" CHAR(8) DEFAULT 'inactive' NOT NULL ENABLE,
    CONSTRAINT "TBL_SKILL_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TBL_SKILL_CHECK" CHECK (STATE IN ('inactive', 'active')) ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- TABLE TBL_POSITION_SKILL
CREATE TABLE EVACOMUNA."TBL_POSITION_SKILL" (
    "POSITIONID" NUMBER(38, 0) NOT NULL ENABLE,
    "SKILLID" NUMBER(38, 0) NOT NULL ENABLE
);

-- TABLE TBL_USER
CREATE TABLE EVACOMUNA."TBL_USER" (
    "ID" NUMBER(38, 0) NOT NULL ENABLE,
    "USERNAME" VARCHAR2(20) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(16) NOT NULL ENABLE,
    "NAME" VARCHAR2(16) NOT NULL ENABLE,
    "LASTNAME" VARCHAR2(16) NOT NULL ENABLE,
    "SECONDLASTNAME" VARCHAR2(16) NOT NULL ENABLE,
    "IDENTIFICATION" VARCHAR2(9) NOT NULL ENABLE,
    "EMAIL" VARCHAR2(64) NOT NULL ENABLE,
    "LANDLINENUMBER" VARCHAR2(8) NOT NULL ENABLE,
    "PHONENUMBER" VARCHAR2(8) NOT NULL ENABLE,
    "PROFILEPHOTO" BLOB,
    "ISACTIVE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
    "ISADMIN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
    "USERPOSITIONID" NUMBER(38, 0) NOT NULL ENABLE,
    CONSTRAINT "TBL_USER_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TBL_USER_UK1" UNIQUE ("USERNAME") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TBL_USER_UK2" UNIQUE ("IDENTIFICATION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" LOB (
    "PROFILEPHOTO"
) STORE AS SECUREFILE (
    TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES
);

-- TABLE TBL_POSITION
CREATE TABLE EVACOMUNA."TBL_POSITION" (
    "ID" NUMBER(*, 0) NOT NULL ENABLE,
    "NAME" VARCHAR2(24) NOT NULL ENABLE,
    "STATE" VARCHAR2(20) DEFAULT 'inactive' NOT NULL ENABLE,
    CONSTRAINT "TBL_POSITION_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TBL_POSITION_CHECK" CHECK (STATE IN ('inactive', 'active')) ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- TABLE TBL_USER_POSITION
CREATE TABLE EVACOMUNA."TBL_USER_POSITION" (
    "ID" NUMBER(38, 0) NOT NULL ENABLE,
    "POSITIONID" NUMBER(38, 0) NOT NULL ENABLE,
    CONSTRAINT "TBL_USER_POSITION_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "USERS" ENABLE
);

-- SEQUENCES

-- SEQ_COMPANY
CREATE SEQUENCE EVACOMUNA.SEQ_COMPANY INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- SEQ_USER_POSITION
CREATE SEQUENCE EVACOMUNA.SEQ_USER_POSITION INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- SEQ_EVALUATION
CREATE SEQUENCE EVACOMUNA.SEQ_EVALUATION INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- SEQ_POSITION
CREATE SEQUENCE EVACOMUNA.SEQ_POSITION INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- SEQ_SKILL
CREATE SEQUENCE EVACOMUNA.SEQ_SKILL INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- SEQ_USER
CREATE SEQUENCE EVACOMUNA.SEQ_USER INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;

-- TRIGGERS

-- TGR_COMPANY
CREATE OR REPLACE TRIGGER TGR_COMPANY BEFORE
    INSERT ON TBL_COMPANY FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN
        :NEW.ID := SEQ_COMPANY.NEXTVAL;
    END IF;
END;
 -- TGR_USER_POSITION
 CREATE OR REPLACE TRIGGER TGR_USER_POSITION BEFORE INSERT ON TBL_USER_POSITION FOR EACH ROW BEGIN IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN :NEW.ID := SEQ_USER_POSITION.NEXTVAL;
END IF;
END;
 -- TGR_EVALUATION
 CREATE OR REPLACE TRIGGER TGR_EVALUATION BEFORE INSERT ON TBL_EVALUATION FOR EACH ROW BEGIN IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN :NEW.ID := SEQ_EVALUATION.NEXTVAL;
END IF;
END;
 -- TGR_POSITION
 CREATE OR REPLACE TRIGGER TGR_POSITION BEFORE INSERT ON TBL_POSITION FOR EACH ROW BEGIN IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN :NEW.ID := SEQ_POSITION.NEXTVAL;
END IF;
END;
 -- TGR_SKILL
 CREATE OR REPLACE TRIGGER TGR_SKILL BEFORE INSERT ON TBL_SKILL FOR EACH ROW BEGIN IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN :NEW.ID := SEQ_SKILL.NEXTVAL;
END IF;
END;
 -- TGR_USER
 CREATE OR REPLACE TRIGGER TGR_USER BEFORE INSERT ON TBL_USER FOR EACH ROW BEGIN IF :NEW.ID IS NULL OR :NEW.ID <= 0 THEN :NEW.ID := SEQ_USER.NEXTVAL;
END IF;
END;
 -- COMMENTS
 COMMENT ON COLUMN EVACOMUNA.TBL_POSITION.STATE IS 'states(inactive, active)';
COMMENT ON COLUMN EVACOMUNA.TBL_SKILL.STATE IS 'states(inactive, active)';
COMMENT ON COLUMN EVACOMUNA.TBL_USER.ISACTIVE IS 'N for false, Y for true';
COMMENT ON COLUMN EVACOMUNA.TBL_USER.ISADMIN IS 'N for false, Y for true';
 -- ALTERS
 -- FK TBL_POSITION_SKILL -> TBL_SKILL
 ALTER TABLE EVACOMUNA."TBL_POSITION_SKILL" ADD CONSTRAINT "FK_TBL_SKILL_TO_POSITION_SKILL" FOREIGN KEY ("SKILLID") REFERENCES EVACOMUNA."TBL_SKILL" ("ID") ENABLE;
 -- FK TBL_POSITION_SKILL -> TBL_POSITION
 ALTER TABLE EVACOMUNA."TBL_POSITION_SKILL" ADD CONSTRAINT "FK_TBL_POSITION_TO_POSITION_SKILL" FOREIGN KEY ("POSITIONID") REFERENCES EVACOMUNA."TBL_POSITION" ("ID") ENABLE;
 -- FK TBL_USER -> TBL_USER_POSITION
 ALTER TABLE EVACOMUNA."TBL_USER" ADD CONSTRAINT "FK_TBL_USER_TO_USER_POSITION" FOREIGN KEY ("USERPOSITIONID") REFERENCES EVACOMUNA."TBL_USER_POSITION" ("ID") ENABLE;
 -- FK TBL_USER_POSITION -> TBL_POSITION
 ALTER TABLE EVACOMUNA."TBL_USER_POSITION" ADD CONSTRAINT "FK_TBL_POSITION_TO_USER_POSITION" FOREIGN KEY ("POSITIONID") REFERENCES EVACOMUNA."TBL_POSITION" ("ID") ENABLE;
 -- FK TBL_EVALUATION -> TBL_USER
 ALTER TABLE EVACOMUNA."TBL_EVALUATION" ADD CONSTRAINT "FK_TBL_USER" FOREIGN KEY ("ID") REFERENCES "EVACOMUNA"."TBL_USER" ("ID") ON DELETE CASCADE ENABLE;
 -- ALTER TRIGGERS
 ALTER TRIGGER EVACOMUNA."TGR_COMPANY" ENABLE;
ALTER TRIGGER EVACOMUNA."TGR_USER_POSITION" ENABLE;
ALTER TRIGGER EVACOMUNA."TGR_EVALUATION" ENABLE;
ALTER TRIGGER EVACOMUNA."TGR_SKILL" ENABLE;
ALTER TRIGGER EVACOMUNA."TGR_POSITION" ENABLE;
ALTER TRIGGER EVACOMUNA."TGR_USER" ENABLE;