-- create the user
CREATE USER UNA
  IDENTIFIED BY UNA
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;

-- grant/revoke role privileges
GRANT RESOURCE TO UNA;

GRANT CONNECT TO UNA;

GRANT DBA TO UNA;

-- grant/revoke system privileges
GRANT CREATE SESSION TO UNA;

GRANT UNLIMITED TABLESPACE TO UNA;