package cr.ac.una.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-08-18T09:18:45.351-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://services.una.ac.cr/", name = "UserServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceImpl {

    @WebMethod
    @Action(input = "http://services.una.ac.cr/UserServiceImpl/getUserRequest", output = "http://services.una.ac.cr/UserServiceImpl/getUserResponse")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://services.una.ac.cr/", className = "cr.ac.una.services.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://services.una.ac.cr/", className = "cr.ac.una.services.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.services.User getUser(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
