CREATE VIEW VIEW_ADMIN_USERS AS
SELECT
    ID,
    USERNAME,
    NAME,
    LASTNAME,
    SECONDLASTNAME,
    IDENTIFICATION,
    EMAIL,
    LANDLINENUMBER,
    PHONENUMBER,
    USERPOSITIONID
FROM EVACOMUNA.TBL_USER
WHERE ISADMIN = 'Y';
