package cr.ac.una.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-09-26T17:48:52.500-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.una.ac.cr/", name = "CalificationController")
@XmlSeeAlso({ObjectFactory.class})
public interface CalificationController {

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/getCalificationByIdRequest", output = "http://controller.una.ac.cr/CalificationController/getCalificationByIdResponse")
    @RequestWrapper(localName = "getCalificationById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetCalificationById")
    @ResponseWrapper(localName = "getCalificationByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetCalificationByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getCalificationById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/deleteCalificationByIdRequest", output = "http://controller.una.ac.cr/CalificationController/deleteCalificationByIdResponse")
    @RequestWrapper(localName = "deleteCalificationById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteCalificationById")
    @ResponseWrapper(localName = "deleteCalificationByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteCalificationByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper deleteCalificationById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/getCalificationNoteRequest", output = "http://controller.una.ac.cr/CalificationController/getCalificationNoteResponse")
    @RequestWrapper(localName = "getCalificationNote", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetCalificationNote")
    @ResponseWrapper(localName = "getCalificationNoteResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetCalificationNoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getCalificationNote(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/getAllCalificationRequest", output = "http://controller.una.ac.cr/CalificationController/getAllCalificationResponse")
    @RequestWrapper(localName = "getAllCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllCalification")
    @ResponseWrapper(localName = "getAllCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getAllCalification()
;

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/updateCalificationRequest", output = "http://controller.una.ac.cr/CalificationController/updateCalificationResponse")
    @RequestWrapper(localName = "updateCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateCalification")
    @ResponseWrapper(localName = "updateCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper updateCalification(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.CalificationDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CalificationController/createCalificationRequest", output = "http://controller.una.ac.cr/CalificationController/createCalificationResponse")
    @RequestWrapper(localName = "createCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCalification")
    @ResponseWrapper(localName = "createCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper createCalification(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.CalificationDto arg0
    );
}
