package cr.ac.una.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-09-10T19:27:44.267-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.una.ac.cr/", name = "CharacteristicController")
@XmlSeeAlso({ObjectFactory.class})
public interface CharacteristicController {

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CharacteristicController/createCharacteristicRequest", output = "http://controller.una.ac.cr/CharacteristicController/createCharacteristicResponse")
    @RequestWrapper(localName = "createCharacteristic", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCharacteristic")
    @ResponseWrapper(localName = "createCharacteristicResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCharacteristicResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper createCharacteristic(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.CharacteristicDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CharacteristicController/selectCharacteristicsRequest", output = "http://controller.una.ac.cr/CharacteristicController/selectCharacteristicsResponse")
    @RequestWrapper(localName = "selectCharacteristics", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.SelectCharacteristics")
    @ResponseWrapper(localName = "selectCharacteristicsResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.SelectCharacteristicsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper selectCharacteristics()
;
}
