package cr.ac.una.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
<<<<<<< HEAD
 * 2023-08-23T19:12:49.009-06:00
=======
 * 2023-08-23T18:23:58.326-06:00
>>>>>>> 53171f5 ([fix]moved controllers)
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "CompanyController",
                  wsdlLocation = "file:/Users/estebannajera/Desktop/tarea-programacion-iii-2023/evacomuna/src/main/resources/cr/ac/una/evacomuna/wsdl/CompanyService.wsdl",
                  targetNamespace = "http://controller.una.ac.cr/")
public class CompanyController_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controller.una.ac.cr/", "CompanyController");
    public final static QName CompanyControllerPort = new QName("http://controller.una.ac.cr/", "CompanyControllerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/estebannajera/Desktop/tarea-programacion-iii-2023/evacomuna/src/main/resources/cr/ac/una/evacomuna/wsdl/CompanyService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CompanyController_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/estebannajera/Desktop/tarea-programacion-iii-2023/evacomuna/src/main/resources/cr/ac/una/evacomuna/wsdl/CompanyService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CompanyController_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CompanyController_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyController_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CompanyController_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CompanyController_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CompanyController_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CompanyController
     */
    @WebEndpoint(name = "CompanyControllerPort")
    public CompanyController getCompanyControllerPort() {
        return super.getPort(CompanyControllerPort, CompanyController.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyController
     */
    @WebEndpoint(name = "CompanyControllerPort")
    public CompanyController getCompanyControllerPort(WebServiceFeature... features) {
        return super.getPort(CompanyControllerPort, CompanyController.class, features);
    }

}
