package cr.ac.una.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
<<<<<<< HEAD
 * 2023-08-23T19:12:48.997-06:00
=======
 * 2023-08-23T18:23:58.312-06:00
>>>>>>> 53171f5 ([fix]moved controllers)
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.una.ac.cr/", name = "CompanyController")
@XmlSeeAlso({ObjectFactory.class})
public interface CompanyController {

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CompanyController/updateCompanyRequest", output = "http://controller.una.ac.cr/CompanyController/updateCompanyResponse")
    @RequestWrapper(localName = "updateCompany", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateCompany")
    @ResponseWrapper(localName = "updateCompanyResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateCompanyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper updateCompany(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.CompanyDto arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/CompanyController/createCompanyRequest", output = "http://controller.una.ac.cr/CompanyController/createCompanyResponse")
    @RequestWrapper(localName = "createCompany", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCompany")
    @ResponseWrapper(localName = "createCompanyResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateCompanyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper createCompany(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.CompanyDto arg0
    );
}
