package cr.ac.una.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-09-26T16:41:10.899-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.una.ac.cr/", name = "EvaluatedController")
@XmlSeeAlso({ObjectFactory.class})
public interface EvaluatedController {

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/createEvaluatedRequest", output = "http://controller.una.ac.cr/EvaluatedController/createEvaluatedResponse")
    @RequestWrapper(localName = "createEvaluated", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateEvaluated")
    @ResponseWrapper(localName = "createEvaluatedResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateEvaluatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper createEvaluated(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.EvaluatedDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/getFinalNoteRequest", output = "http://controller.una.ac.cr/EvaluatedController/getFinalNoteResponse")
    @RequestWrapper(localName = "getFinalNote", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalNote")
    @ResponseWrapper(localName = "getFinalNoteResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalNoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getFinalNote(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/updateEvaluatedRequest", output = "http://controller.una.ac.cr/EvaluatedController/updateEvaluatedResponse")
    @RequestWrapper(localName = "updateEvaluated", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateEvaluated")
    @ResponseWrapper(localName = "updateEvaluatedResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateEvaluatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper updateEvaluated(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.EvaluatedDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/deleteEvaluatedByIdRequest", output = "http://controller.una.ac.cr/EvaluatedController/deleteEvaluatedByIdResponse")
    @RequestWrapper(localName = "deleteEvaluatedById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteEvaluatedById")
    @ResponseWrapper(localName = "deleteEvaluatedByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteEvaluatedByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper deleteEvaluatedById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/getEvaluatedByIdRequest", output = "http://controller.una.ac.cr/EvaluatedController/getEvaluatedByIdResponse")
    @RequestWrapper(localName = "getEvaluatedById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetEvaluatedById")
    @ResponseWrapper(localName = "getEvaluatedByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetEvaluatedByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getEvaluatedById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/EvaluatedController/getAllEvaluatedRequest", output = "http://controller.una.ac.cr/EvaluatedController/getAllEvaluatedResponse")
    @RequestWrapper(localName = "getAllEvaluated", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllEvaluated")
    @ResponseWrapper(localName = "getAllEvaluatedResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllEvaluatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getAllEvaluated()
;
}
