package cr.ac.una.controller;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-09-26T16:41:11.668-06:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://controller.una.ac.cr/", name = "FinalCalificationController")
@XmlSeeAlso({ObjectFactory.class})
public interface FinalCalificationController {

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/getFinalCalificationNoteRequest", output = "http://controller.una.ac.cr/FinalCalificationController/getFinalCalificationNoteResponse")
    @RequestWrapper(localName = "getFinalCalificationNote", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalCalificationNote")
    @ResponseWrapper(localName = "getFinalCalificationNoteResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalCalificationNoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getFinalCalificationNote(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/getAllFinalCalificationRequest", output = "http://controller.una.ac.cr/FinalCalificationController/getAllFinalCalificationResponse")
    @RequestWrapper(localName = "getAllFinalCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllFinalCalification")
    @ResponseWrapper(localName = "getAllFinalCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAllFinalCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getAllFinalCalification()
;

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/createFinalCalificationRequest", output = "http://controller.una.ac.cr/FinalCalificationController/createFinalCalificationResponse")
    @RequestWrapper(localName = "createFinalCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateFinalCalification")
    @ResponseWrapper(localName = "createFinalCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.CreateFinalCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper createFinalCalification(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.FinalCalificationDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/deleteFinalCalificationByIdRequest", output = "http://controller.una.ac.cr/FinalCalificationController/deleteFinalCalificationByIdResponse")
    @RequestWrapper(localName = "deleteFinalCalificationById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteFinalCalificationById")
    @ResponseWrapper(localName = "deleteFinalCalificationByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.DeleteFinalCalificationByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper deleteFinalCalificationById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/updateFinalCalificationRequest", output = "http://controller.una.ac.cr/FinalCalificationController/updateFinalCalificationResponse")
    @RequestWrapper(localName = "updateFinalCalification", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateFinalCalification")
    @ResponseWrapper(localName = "updateFinalCalificationResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.UpdateFinalCalificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper updateFinalCalification(

        @WebParam(name = "arg0", targetNamespace = "")
        cr.ac.una.controller.FinalCalificationDto arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/getAverageRequest", output = "http://controller.una.ac.cr/FinalCalificationController/getAverageResponse")
    @RequestWrapper(localName = "getAverage", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAverage")
    @ResponseWrapper(localName = "getAverageResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetAverageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getAverage(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://controller.una.ac.cr/FinalCalificationController/getFinalCalificationByIdRequest", output = "http://controller.una.ac.cr/FinalCalificationController/getFinalCalificationByIdResponse")
    @RequestWrapper(localName = "getFinalCalificationById", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalCalificationById")
    @ResponseWrapper(localName = "getFinalCalificationByIdResponse", targetNamespace = "http://controller.una.ac.cr/", className = "cr.ac.una.controller.GetFinalCalificationByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cr.ac.una.controller.ResponseWrapper getFinalCalificationById(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
